/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package softwaretestingclient;

import java.awt.Color;

/**
 *
 * @author Nichlas
 */
public class ForgotPWFrame extends javax.swing.JFrame {

    public ForgotPWFrame() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        EmailTxt = new javax.swing.JTextField();
        OKBtn = new javax.swing.JButton();
        ErrorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Forgot Password");

        jLabel2.setText("A new password will be send to your email, if you have a valid account");

        jLabel3.setText("Email:");

        OKBtn.setText("OK");
        OKBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKBtnActionPerformed(evt);
            }
        });

        ErrorLabel.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(OKBtn)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(EmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ErrorLabel))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(EmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OKBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ErrorLabel)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKBtnActionPerformed
        // TODO add your handling code here:
        if (valEmail(EmailTxt.getText()) == false) {
            ErrorLabel.setForeground(Color.RED);
            ErrorLabel.setText("Not a correct email try again.");
        }else{
            
            String newPW = passwordGen();
            
            if (changePassword(EmailTxt.getText() , newPW)==false) {
                ErrorLabel.setForeground(Color.BLUE);
                ErrorLabel.setText("Password send to Email!");
            }else{
                ErrorLabel.setForeground(Color.BLUE);
                sendPassword(EmailTxt.getText(), newPW);
                ErrorLabel.setText("Password send to Email!");
            }
            
        }
    }//GEN-LAST:event_OKBtnActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmailTxt;
    private javax.swing.JLabel ErrorLabel;
    private javax.swing.JButton OKBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    private static String passwordGen() {
        service.LoginWebService_Service service = new service.LoginWebService_Service();
        service.LoginWebService port = service.getLoginWebServicePort();
        return port.passwordGen();
    }

    private static Boolean changePassword(java.lang.String arg0, java.lang.String arg1) {
        service.LoginWebService_Service service = new service.LoginWebService_Service();
        service.LoginWebService port = service.getLoginWebServicePort();
        return port.changePassword(arg0, arg1);
    }

    private static void sendPassword(java.lang.String arg0, java.lang.String arg1) {
        service.LoginWebService_Service service = new service.LoginWebService_Service();
        service.LoginWebService port = service.getLoginWebServicePort();
        port.sendPassword(arg0, arg1);
    }

    private static boolean valEmail(java.lang.String arg0) {
        service.LoginWebService_Service service = new service.LoginWebService_Service();
        service.LoginWebService port = service.getLoginWebServicePort();
        return port.valEmail(arg0);
    }
}
