/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package softwaretestingclient;






/**
 *
 * @author Nichlas
 */
public class LoginScreen extends javax.swing.JFrame {

    /**
     * Creates new form LoginScreen
     */
    public LoginScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        logPassword = new javax.swing.JTextField();
        LogUsername = new javax.swing.JTextField();
        LoginBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        regUsername = new javax.swing.JTextField();
        regPassword = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        RegisterBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        InfoText = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        ErrorText = new javax.swing.JTextPane();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        regEmail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ForgotEmail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        SendPasswordBtn = new javax.swing.JButton();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LoginBtn.setText("Login");
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Email");

        jLabel2.setText("Password");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        regUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regUsernameActionPerformed(evt);
            }
        });

        regPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regPasswordActionPerformed(evt);
            }
        });

        jLabel4.setText("Register");

        jLabel6.setText("Username");

        jLabel7.setText("Password");

        RegisterBtn.setText("Register");
        RegisterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterBtnActionPerformed(evt);
            }
        });

        InfoText.setEditable(false);
        InfoText.setText("* Username must be between 6 and 12 charecters long\n* Username can only contain normal characters and numbers\n* Password must be atleast 8 characters long\n* Password must contain one uppercase and one lowercase\n* Must be a valid Email\n");
        jScrollPane1.setViewportView(InfoText);

        ErrorText.setEditable(false);
        jScrollPane2.setViewportView(ErrorText);

        jLabel8.setText("Login");

        jLabel9.setText("Error Box");

        regEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regEmailActionPerformed(evt);
            }
        });

        jLabel10.setText("Email");

        jLabel11.setText("Forgot your Password?");

        jLabel12.setText("Enter your registered Email here.");

        SendPasswordBtn.setText("Send password");
        SendPasswordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendPasswordBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel1)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jLabel3))
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(LogUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LoginBtn)
                            .addComponent(logPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(jLabel4))
                            .addComponent(jLabel6)
                            .addComponent(regUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(regEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(regPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(ForgotEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SendPasswordBtn)))
                    .addComponent(RegisterBtn)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel1)
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)))
                        .addComponent(LogUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel2)
                        .addGap(6, 6, 6)
                        .addComponent(logPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(34, 34, 34))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LoginBtn)
                                .addGap(18, 18, 18)))
                        .addComponent(jLabel9)
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel4)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6)
                        .addGap(6, 6, 6)
                        .addComponent(regUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel10)
                        .addGap(4, 4, 4)
                        .addComponent(regEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel7)
                        .addGap(6, 6, 6)
                        .addComponent(regPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RegisterBtn)
                        .addGap(59, 59, 59)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel11)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel12)
                        .addGap(4, 4, 4)
                        .addComponent(ForgotEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SendPasswordBtn)))
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regUsernameActionPerformed

    private void regPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regPasswordActionPerformed

    private void RegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterBtnActionPerformed
        if(!checkEmailExist(regEmail.getText()) && registrate(regUsername.getText(), regEmail.getText(), regPassword.getText())){
            ErrorText.setText("Succes Registration! An Email has been send");
            welcomeMail(regEmail.getText());// ----> ACTIVATE WHEN DONE
        }else{     
            ErrorText.setText("Username Already exist! Try another");
            if (valUsername(regUsername.getText()) == false) {
                ErrorText.setText("Username does not fulfill the requirements!!");
            }else if (checkEmailExist(regEmail.getText())) {
                ErrorText.setText("Email already exist in database");
            }else if (valEmail(regEmail.getText())== false) {
                ErrorText.setText("Email does not fulfill the requirements!!");
            }else if (valPassword(regPassword.getText())== false) {
                ErrorText.setText("Password does not fulfill the requirements!!");
            }
        }
    }//GEN-LAST:event_RegisterBtnActionPerformed

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        if(login(LogUsername.getText(), logPassword.getText())){
            ErrorText.setText("Succes login");
        }else{     //Add Error Handling!!!!
            ErrorText.setText("Error login");
        }
        
    }//GEN-LAST:event_LoginBtnActionPerformed

    private void regEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regEmailActionPerformed

    private void SendPasswordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendPasswordBtnActionPerformed
        if (valEmail(ForgotEmail.getText()) == false) {
            ErrorText.setText("Not a correct email try again.");
        }else{
            
            String newPW = passwordGen();
            
            if (changePassword(ForgotEmail.getText() , newPW)==false) {
                ErrorText.setText("Email not found!");
            }else{
                sendPassword(ForgotEmail.getText(), newPW);
                ErrorText.setText("Password send to Email!");
            }
            
        }
    }//GEN-LAST:event_SendPasswordBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
      
       // System.out.println(hello("Nica"));
       // System.out.println(login("123", "123"));
      //  System.out.println(validatePassword("123a"));
       // System.out.println(validateEmail("123a"));
        //System.out.println(valUsername("123a"));
        //System.out.println(passwordGen());
        //System.out.println(valEmail("sadasd@gmail.com.asd"));
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginScreen().setVisible(true);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane ErrorText;
    private javax.swing.JTextField ForgotEmail;
    private javax.swing.JTextPane InfoText;
    private javax.swing.JTextField LogUsername;
    private javax.swing.JButton LoginBtn;
    private javax.swing.JButton RegisterBtn;
    private javax.swing.JButton SendPasswordBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField logPassword;
    private javax.swing.JTextField regEmail;
    private javax.swing.JTextField regPassword;
    private javax.swing.JTextField regUsername;
    // End of variables declaration//GEN-END:variables

    private static boolean login(java.lang.String arg0, java.lang.String arg1) {
        service.LoginWebService_Service service = new service.LoginWebService_Service();
        service.LoginWebService port = service.getLoginWebServicePort();
        return port.login(arg0, arg1);
    }

    private static boolean registrate(java.lang.String arg0, java.lang.String arg1, java.lang.String arg2) {
        service.LoginWebService_Service service = new service.LoginWebService_Service();
        service.LoginWebService port = service.getLoginWebServicePort();
        return port.registrate(arg0, arg1, arg2);
    }

    private static boolean valEmail(java.lang.String arg0) {
        service.LoginWebService_Service service = new service.LoginWebService_Service();
        service.LoginWebService port = service.getLoginWebServicePort();
        return port.valEmail(arg0);
    }

    private static boolean valPassword(java.lang.String arg0) {
        service.LoginWebService_Service service = new service.LoginWebService_Service();
        service.LoginWebService port = service.getLoginWebServicePort();
        return port.valPassword(arg0);
    }

    private static boolean valUsername(java.lang.String arg0) {
        service.LoginWebService_Service service = new service.LoginWebService_Service();
        service.LoginWebService port = service.getLoginWebServicePort();
        return port.valUsername(arg0);
    }

    private static void welcomeMail(java.lang.String arg0) {
        service.LoginWebService_Service service = new service.LoginWebService_Service();
        service.LoginWebService port = service.getLoginWebServicePort();
        port.welcomeMail(arg0);
    }

    private static String passwordGen() {
        service.LoginWebService_Service service = new service.LoginWebService_Service();
        service.LoginWebService port = service.getLoginWebServicePort();
        return port.passwordGen();
    }

    private static Boolean checkEmailExist(java.lang.String arg0) {
        service.LoginWebService_Service service = new service.LoginWebService_Service();
        service.LoginWebService port = service.getLoginWebServicePort();
        return port.checkEmailExist(arg0);
    }

    private static void sendPassword(java.lang.String arg0, java.lang.String arg1) {
        service.LoginWebService_Service service = new service.LoginWebService_Service();
        service.LoginWebService port = service.getLoginWebServicePort();
        port.sendPassword(arg0, arg1);
    }

    private static Boolean changePassword(java.lang.String arg0, java.lang.String arg1) {
        service.LoginWebService_Service service = new service.LoginWebService_Service();
        service.LoginWebService port = service.getLoginWebServicePort();
        return port.changePassword(arg0, arg1);
    }
    


}
